server:
  port: 8080

spring:
  application:
    name: msa-api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  ignored-services: '*' #route 패턴 외 무시
  routes:
    msa-lpm-api:
      path: /lpm/**
      serviceId: msa-lpm-api
      stingPrefix: false
  host:
    max-total-connections: 10000
    max-per-route-connections: 50
ribbon:
  eureka:
    enabled: true
